INSERT INTO pertanyaan (teks_pertanyaan, kategori) VALUES
(N'Apakah kamu tertarik membuat website?', N'web'),
(N'Apakah kamu senang mengatur tampilan halaman (warna, layout, font)?', N'web'),
(N'Apakah kamu tertarik mempelajari HTML, CSS, dan JavaScript?', N'web'),
(N'Apakah kamu senang membuat fitur interaktif pada website?', N'web'),
(N'Apakah kamu tertarik menggunakan framework seperti Bootstrap, React, atau Laravel?', N'web'),
(N'Apakah kamu senang melihat dan mencoba website baru untuk dipelajari cara kerjanya?', N'web'),
(N'Apakah kamu sudah bisa membuat struktur halaman menggunakan HTML?', N'web'),
(N'Apakah kamu bisa mengatur tampilan website menggunakan CSS?', N'web'),
(N'Apakah kamu bisa membuat interaksi sederhana dengan JavaScript?', N'web'),
(N'Apakah kamu pernah membuat proyek website sederhana sendiri?', N'web'),
(N'Apakah kamu memahami dasar kerja backend (server, database, API)?', N'web'),
(N'Apakah kamu bisa memperbaiki error (bug) sederhana pada kode website?', N'web'),
(N'Apakah kamu tertarik mempelajari deployment dan hosting?', N'web'),
(N'Apakah kamu tertarik pada aspek keamanan website (basic)?', N'web'),
(N'Apakah kamu nyaman bekerja dengan tools developer (browser devtools, console)?', N'web'),
(N'Apakah kamu tertarik belajar version control (Git)?', N'web'),
(N'Apakah kamu suka belajar framework front-end (React/Vue)?', N'web'),
(N'Apakah kamu suka belajar framework back-end (Node/PHP/ASP.NET)?', N'web'),
(N'Apakah kamu suka dokumentasi dan menulis README untuk proyek?', N'web'),
(N'Apakah kamu tertarik mengoptimasi performa website?', N'web');
